### PR TITLE
Normalized cut

### PR DESCRIPTION
**Pull request by yuj18**
Note: This module makes use of R's irlba package (https://cran.r-project.org/web/packages/irlba/index.html) for fast approximate SVD for sparse matrices. It therefore requires PL/R and the irlba package to be installed first.

### CODE REVIEW

**Comment by vatsan** [comment]
@yuj18 @asong92 
Not my business anymore, but IMO you guys will have to first modify pdlpack.py to check for PL/R + your R library dependency before introducing PL/R modules or any other R/Python library that's not part of the standard install. If you don't, then PDLTools installs will be broken i.e. the installation will indicate all is well, until someone runs the specific UDF which will crap out complaining it couldn't find a library. The more users write UDFs that rely on PL/R (or Python libraries not part of the standard install), the more unreliable will the user experience be. There won't be one source of truth as to what in PDLTools will work out of the box. I encourage you guys to focus on more stabler and reliable releases before more features :-)

**Comment by asong92** [comment]
@vatsan thanks!! I'll go and do that before releasing the new version :)

**Comment by vatsan** [comment]
@asong92 
Cool. Basically pdlpack should check if:
1. PL/R is installed.
2. The R library that Jin is using is installed.
If neither of those are installed, it should print a message and not install the corresponding UDFs.

Make sure to update the doxygen docs for these modules to reflect the dependency on PL/R and the corresponding R library.

**Comment by asong92** [comment]
@vatsan 
Done! 
https://github.com/pivotalsoftware/PDLTools/commit/906071bcf88ddd45cf0d7b6b64b1711875d1ae1c

**Comment by yuj18** [comment]
@vatsan: You just can't help but still help us : ) Thanks!!!

I was also a bit hesitate over whether to merge this new module to the
master branch due to the same reason. But I think (hope) that the algorithm
would be quite useful for a lot of use cases; for example, @asong92 will
use it to produce high-level groupings of data for large-scale clustering
problems.

I pointed Frank to the particular SVD package I used. It's much more
scalable than the standard SVD implementation in MADlib. Hopefully we'll
have it in MADlib someday. Then we don't have to use the R package.

**Comment by vatsan** [comment]
Yes, we've benchmarked irlba against MADlib long ago, they are aware of how
much better it is.

**Pull request merged**
